server:
  port: 8084
spring:
  application:
    name: payment

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://54.176.95.76:8761/eureka