server:
  port: 8084
spring:
  application:
    name: payment

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://13.57.146.21:8761/eureka