server:
  port: 8086
spring:
  data:
    mongodb:
      host: 13.57.146.21
      port: 27017
      database: chat
  application:
    name: chat-service
  cloud:
    config:
      uri: http://13.57.146.21:8888
      import-check.enabled: false
management:
  security:
    enabled: false
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://13.57.146.21:8761/eureka
