server:
  port: 8086
spring:
  data:
    mongodb:
      host: 54.176.95.76
      port: 27017
      database: chat
  application:
    name: chat-service
  cloud:
    config:
      uri: http://54.176.95.76:8888
      import-check.enabled: false
management:
  security:
    enabled: false
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://54.176.95.76:8761/eureka
