server:
  port: 8082
  
spring:
  application:
    name: team-up
  data:
    mongodb:
      host: 54.176.95.76
      port: 27017
      database: TeamupDB

  rabbitmq:
    port: 5672
    host: 54.176.95.76
    username: guest
    password: guest

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://54.176.95.76:8761/eureka

# spring:
#   application:
#     name: team-up
#   cloud:
#     config:
#       uri: http://localhost:8888
#       import-check:
#         enabled: false
#     mangement:
#       security:
#         enabled: false
